### ISSUE TITLE
Number on Regex Example

### ISSUE THREAD

**Issue by divyanshmanocha** [LangProc/langproc-2017-lab#1]
I might be wrong, however there appears to be a mistake with the example you have given us.

```
Given the input:

a a a aa -67  -80 -6780 for while
"  x",, 52x
The output would be:

-6785
"  x" 1
"a" 2
"aa" 1
"for" 1
"while" 1
"x" 1
```

Should the number not be -6875?

**Comment by m8pple** [comment]
Yes, you're right. Looks like I transposed the two inner digits when
typing them in (why I didn't copy and paste... who knows).

Thanks - let me know if you see anything else.
