### ISSUE TITLE
Git Commands

### ISSUE THREAD

**Issue by luisi-at** [LangProc/langproc-2017-lab#10]
Some of the git commands have the wrong syntax in section a, for instance I believe `git remote pull spec` should be `git pull spec master`

`git remote pull spec` gives the following error on OS X:

<img width="798" alt="screen shot 2017-01-18 at 09 21 28" src="https://cloud.githubusercontent.com/assets/17338500/22058094/a85b1d32-dd5f-11e6-9f9c-e4fe3c0f0cda.png">

**Comment by ThunderMikey** [comment]
Same issue on Ubuntu

**Comment by m8pple** [comment]
Sorry, I missed this issue when it went up. Thanks for the correction, I'll update it.
