### ISSUE TITLE
Intermediate: C++ regexes (20%) Section End Missing?

### ISSUE THREAD

**Issue by Odog1996** [LangProc/langproc-2017-lab#14]
Nothing major, but the last line of text before the advanced section ends with: "You might wish to adapt the test infrastructure from part a to help you, or create some other simple way of checking that your" and nothing else.

**Comment by m8pple** [comment]
Thanks, I hadn't noticed that.

It was also caught by @ps-george, so was fixed in their PR at e4d00b3c2847977bb6a4d54906464635d5711146.
