### ISSUE TITLE
Trying to write test script

### ISSUE THREAD

**Issue by ps-george** [LangProc/langproc-2017-lab#19]
I'm trying to write a script to generate ref files for the regex_substitute_ref.sh, but the output of is always just identical to the input.

When I `echo ${sedpattern[0]} ${sedpattern[1]};` I get

"First[^a-z]*([a-z][a-z0-9]*).*[.]pdf" "\1.pdf"

But then the command:  `"First_dt10_v3.pdf | ./regex_substitute_ref.sh "${sedpattern[0]}" "${sedpattern[1]}"` just outputs the same as the input.

``` bash
for i in test/in/*.txt; do
  echo "Input file : ${i}"
  exec 6< $i
  read -a sedpattern <&6
  echo ${sedpattern[0]} ${sedpattern[1]};
     
  BASENAME=$(basename $i .txt);
  "First_dt10_v3.pdf | ./regex_substitute_ref.sh "${sedpattern[0]}" "${sedpattern[1]}" > test/ref/$BASENAME.txt

  exec 6<&- 
done
```

**Comment by Carotti** [comment]
I think you're probably looking for [eval](http://wiki.bash-hackers.org/commands/builtin/eval).

Try changing
`./regex_substitute_ref.sh "${sedpattern[0]}" "${sedpattern[1]}"`
to
`eval ./regex_substitute_ref.sh "${sedpattern[0]}" "${sedpattern[1]}"`
