### ISSUE TITLE
Test #8

### ISSUE THREAD

**Issue by martinferianc** [LangProc/langproc-2017-lab#2]
The test 08.txt contains:

-1

But the 08.stdout.txt in /ref contains:

1.000

Isn't that a mistake?

Thanks!

**Comment by m8pple** [comment]
Yes, you're right. 

When I prepare the exercise, I do the reference implementation, then "degrade" it to provide
the skeleton. It looks like I somehow generated the reference outputs from a partially
degraded version, which didn't have a full number regex.

I'll check the other ones too.

Did you get that from visual inspection, or did your version come up with a different answer?

Sorry, forgot to say thanks!

**Comment by m8pple** [comment]
Yup, looks like there are errors in 11, 13, 14, and 27, for the same reason.
