### ISSUE TITLE
Clarifications lab 2

### ISSUE THREAD

**Issue by ml7715** [LangProc/langproc-2017-lab#22]
Could you specify whether the function `log` indicates a natural logarithm or a log base 10?
The maths lexer does not seem to catch new lines.

**Comment by m8pple** [comment]
I'll clarify the that log is natural log in the text.

I don't suppose you'd mind doing a pull request for adding a
newline catcher to the default flex file? I'm not sure when I'll
next get in front of an ubuntu VM to check any changes in
the code, and I don't really want to edit that part without
testing, so it would be helpful if you're able to add it.

Don't worry if not.
