### ISSUE TITLE
Deadline for testing part (a) labs is too early

### ISSUE THREAD

**Issue by drovick** [LangProc/langproc-2017-lab#25]
I spoke to you at the end of the Lecture today about this. I, and potentially other students, will not be able to make the 10pm deadline tonight for being run through your test bench. Would it be possible to change the deadline to tomorrow, or do an additional run of tests tomorrow, preferably also at 10pm?

**Comment by m8pple** [comment]
Yes, I added a comment about other times I would pull, it is included
in the readme of lab1/a

I've changed the title, as:
- These are not deadlines
- They are not formal testing
