### ISSUE TITLE
How do we input to the parser on command line?

### ISSUE THREAD

**Issue by ps-george** [LangProc/langproc-2017-lab#28]
When I type in this: 
````
$ bin/print_canonical
x+6
````
I get nothing. When I type in this however,
`$ echo "x+6" | ./bin/print_canonical`

I get the desired result.

I can also press Ctrl+D (Unix), but then:
````
$ bin/print_canonical
x+6 ^D
````
Gives me (the input and output end up on the same line):
````
$ bin/print_canonical
x+6 ( x + 6 )
````
And:
````
$ bin/print_canonical
x+6
^D
````
Gives me (Output ends up two lines below the input):
````
$ bin/print_canonical
x+6

( x + 6 )
````

How are we supposed to get input and output matching the specification?

**Comment by m8pple** [comment]
I think must have taken liberties with the formatting to make it look
cleaner - I was using ctrl-d to terminate the input, and must have
deleted the blank line when moving it to markdown.

Presumably the test-suite is saying your implementation is ok?
