### ISSUE TITLE
Strange bug with print() function for maths parser

### ISSUE THREAD

**Issue by ps-george** [LangProc/langproc-2017-lab#30]
Flow:
```` cpp
ast->print();
while(){
  fprintf(stderr, "%d changes", c);
}
fprintf(stderr, "\n");
````
Output:
````
0 ) ) ) ) 

158 changes
3 changes
1 changes
0 changes

)
````

This is solved by printing a newline to stdout after `ast->print();`

I have no idea why... stdout buffer needs emptying or something like that?

**Comment by m8pple** [comment]
stdout is a buffered stream - usually line buffered
if it can work out that the output is interactive (i.e.
a terminal):
http://stackoverflow.com/questions/3723795/is-stdout-line-buffered-unbuffered-or-indeterminate-by-default

So if you want stdout to be flushed during execution, then
you can print a newline to stdout, or use fflush(), to force
the output to appear.

It should also be flushed at the end of the program, under
normal exit conditions. If you find that the program doesn't
print output when it exits, but does if you add the newline,
then it may be that your program is crashing. This can happen
when objects are destructed at the end of main, and if
something blows up before the c standard library flushes
the buffer, the output will be lost.

If that is happening, you might want to check if your
AST has got corrupted in some way, and check the exit
code ($?) of your program on the shell.

David Thomas

**Comment by ps-george** [comment]
Seemed to be the buffer from the stdout hadn't been flushed. 

If I use `std::cerr`, or `fflush()` or have the newline in it works fine.
