### ISSUE TITLE
How do you want us to set up the makefile for part c?

### ISSUE THREAD

**Issue by tnugent97** [LangProc/langproc-2017-lab#32]
For part c you want us to create a new file called diff_expr.cpp, so I assume this should be able to be compiled and run by writing:
```
make bin/diff_expr
bin/diff_expr
```
from the command line? (obviously when running you'd have parameters .etc)

**Comment by fexter-svk** [comment]
It is compiled if you run the test_parser.sh. Only make sure that it has that name. :)

**Comment by tnugent97** [comment]
@fexter-svk That's only for part a isn't it? I'm talking about part c

**Comment by fexter-svk** [comment]
test_parser.sh: 
```
make bin/print_canonical -B
make bin/eval_expr -B
make bin/diff_expr -B`
```
makefile:
```
bin/diff_expr : src/diff_expr.o src/maths_parser.tab.o src/maths_lexer.yy.o src/maths_parser.tab.o
		mkdir -p bin
		g++ $(CPPFLAGS) -o bin/diff_expr $^
```

**Comment by tnugent97** [comment]
Is that something you've added? I can't find it in the code:
[CLICK HERE FOR DA CODE](https://github.com/LangProc/langproc-2016-lab/blob/master/2-parsers/test_parser.sh)

**Comment by martinferianc** [comment]
Sorry, it is mine, I did not even realise :(
