### ISSUE TITLE
How to differentiate?

### ISSUE THREAD

**Issue by louiskueh** [LangProc/langproc-2017-lab#34]
For part 3 I've been trying to work out how to get to the example case :

```
$ bin/diff_expr x y x
x*(x+2*y)*x/z*x + y *x
12*x/z
$
```
I've tried getting to the example case 

![](https://cloud.githubusercontent.com/assets/2521843/22745651/37b4031c-ee19-11e6-95b4-8a7d756f94d0.jpg)

But I get **-6(x^2 / z^2)** as shown above

* I have looked through the lecture slides and it's the same with what I did.
* I noticed that if you differentiate the answer with respect to x , y then x again you obtain the example case (or y, x then x)

Am I missing something or have I forgotten how to differentiate ?

Thanks

**Comment by Carotti** [comment]
> I noticed that if you differentiate the answer with respect to x , y then x again you obtain the example case (or y, x then x)

I'm pretty sure this is what you're meant to do!

From

> $ bin/diff_expr x y x

It's saying to differentiate with respect to x, then y, then x

**Comment by louiskueh** [comment]
Oh...

I should read next time

Cheers
