### ISSUE TITLE
codegen: ISA reference incorrect

### ISSUE THREAD

**Issue by lorenzo2897** [LangProc/langproc-2017-lab#39]
In the [section](https://github.com/LangProc/langproc-2016-lab/tree/master/3-codegen#basic-part-2-30-code-generation) detailing supported assembly instructions, the `beq` and `bne` instructions are defined with the wrong register names.

`beq dstReg srcRegA label` should be `beq srcRegA srcRegB label`

`bne dstReg srcRegA label` should be `bne srcRegA srcRegB label`

**Comment by m8pple** [comment]
Ah - that is leftover from when I was trying to come up with the
simplest ISA that allowed interesting behaviour.

Thanks.
