### ISSUE TITLE
Issues with script file

### ISSUE THREAD

**Issue by divyanshmanocha** [LangProc/langproc-2017-lab#4]
Hi,

There seem to be some issues with the script file. I have listed them below. I am not creating a pull request, as these may be major changes that I am not certain about.

1. Your diff's are extremely strict at the moment. Perhaps on purpose? For example consider ref 07, if there is no new line after 1.000, the diff outputs a distinction which your script file catches. Would it be better to add -Z or/and -B option to the diff?

2. The Make clean sometimes deletes the Histogram executable after which it strangely fails to run, in which case I have to manually make histogram and rerun the script.

3. Stdout does not work properly in my case. It seems to output a blank space, even though the yytext has an output (tested by redirecting to stderr). I am not sure how to correct this.

You may also want to add to the instructions to change the permission of ./test_lexer.sh using chmod +x since direct Git pull requests do not allow it to run. Alternatively bash ./test_lexer.sh can be used.

**Comment by divyanshmanocha** [comment]
For number 2. I think the error occurs when the script continues running after make failure. In particular:

Maybe something like this may help to prevent this situation for others?:
```Make
make histogram -B
if [[ "$?" -ne 0 ]]; then
    echo "Build failed.";
    exit;
fi
```
or:
```Make make histogram -B || exit ```

**Comment by m8pple** [comment]
Looking at them in turn:

1 - It's strict on purpose. The general convention is that in posix a line is terminated
     by a newline, and the last line should also have a newline. While we don't usually
     thing of it in the same way, a newline is a bit like the C semi-colon - it is a terminator,
     not a separator.

2 - Yes, I should probably have added an `exit` there. I actually put it in for the
     [lab3 equivalent](https://github.com/LangProc/langproc-2016-lab/blob/master/3-codegen/test_interpreter.sh#L14). Part of the problem of creating test scripts that work both
     for assesement and for student use is that they are used in quite different ways, so
     I would tend to look at the output as a file (with the first failure at the top), while if you're
     running it you tend to see the last thing printed at the bottom.

    I'll add it in.

3 - Not sure what you mean by that. Is it a problem with the output of your lexer, or in the
     way the script is comparing the output with the reference output?

4 - I think the permissions thing is my fault for mixing windows/linux. I've got so used to
     typing `chmod u+x whatever` that I don't actually know I'm doing it. I'll try to be more
    careful on check-in, and also add some notes to the readme about it.

Thanks for those. It's really helpful to find these things out before the lab tomorrow, as they're
the kinds of things that we (me + helpers) tend not to notice.

**Comment by m8pple** [comment]
I think these have all been handled, so I'm closing.

Feel free to re-open if I missed one.
