### ISSUE TITLE
codegen: scope of variables

### ISSUE THREAD

**Issue by lorenzo2897** [LangProc/langproc-2017-lab#40]
The spec is a bit unclear on the notion of scope, and whether variables are only relevant to the branch that they belong to.

Several factors would suggest that _all variables have global scope_:

* Since variables need not be declared before they are assigned, transporting values from an inner scope to an outer scope would require pre-assigning dummy values to variables at the outer scope.

* Introducing scopes would make functional constructs such as `Add [ Add [ Assign x : [ Input ] 1 ] x ]` (double the input and add 1) behave un-intuitively, since x would go out of scope before the second Add could access it.

* The code in the compiler stub does not currently deal with scope when accessing variables

Could you confirm that this assumption is correct?

**Comment by m8pple** [comment]
Yes, you are correct - it is implicitly the case that variables have global scope,
for all three reasons suggested. It should have been explicit, as trying to manage
complexity and minimise effort is one of the goals for this lab.

Good catch - I'll update the spec to make this clear, as in the context of the
lecture talking about scopes this does end up looking ambiguous.
