### ISSUE TITLE
codegen: MIPS toolchain

### ISSUE THREAD

**Issue by lorenzo2897** [LangProc/langproc-2017-lab#41]
In part C of the code generation lab, we are required to use a MIPS toolchain to complete the task.

Can we assume that the apt package **gcc-mips-linux-gnu** is installed on the target machine for our program, with the ability to call binaries such as `mips-linux-gnu-gcc`, `mips-linux-gnu-as`, and  `mips-linux-gnu-ld`?

**Comment by m8pple** [comment]
Yes, you can assume it is always installed.

The lab Ubuntu machines should all have installed (as I required ICT to install it for this course and arch2), and the Vagrant Ubuntu machine should install the toolchain automatically as part of the provisioning
process.
