### ISSUE TITLE
Initial Compilation

### ISSUE THREAD

**Issue by luisi-at** [LangProc/langproc-2017-lab#42]
I had to add `mkdir -p bin` in the script for the code to run 'out of the box'. Clang was failing to find the folder to do the force build for `bin/interpreter`. Was the script meant to do this or was there meant to be a `bin` folder in place to start with?

**Comment by m8pple** [comment]
That's a bug in the script.

I just encountered this while triaging something else. It looks like in my reference build
(i.e. my solutions to the problems) I'd added a `bin/.gitignore`, but this didn't get copied
back to the spec version (I'm always a bit worried about accidentally copying reference
solutions back to the spec).

I'll use the `mkdir -p bin` fix here, as it is a bit less invasive.
