### ISSUE TITLE
Over-write files in Code analysis?

### ISSUE THREAD

**Issue by divyanshmanocha** [LangProc/langproc-2017-lab#46]
Do you want us to over-write the current test files  in Code analysis? Or should we duplicate them and run tests from there.
The latter makes more sense to me, as false input tests will change the results of the previous two exercises.

**Comment by m8pple** [comment]
Do you should you add new test files into './3-codegen/test/programs'?

From the point of view of assessment, I believe that my top-level script will
overwrite that directory before calling `test_interpreter.sh` (as well as over-writing
`test_interpreter.sh`).

I think I agree with the duplication argument, which I assume means to
take the contents of `./3-codegen/test/programs` and copy it to something
like `/3-codegen/test/analysis`, then modify the test inputs as needed?
