### ISSUE TITLE
Is "constant" the same as "decimalNumber"?

### ISSUE THREAD

**Issue by fpgamy** [LangProc/langproc-2017-lab#48]
In the examples, cases where optimisations could be made with dead branch removal have constants as the condition and are of type decimalNumber. If for example the condition is constant, but not a decimalNumber is it expected for the dead branch to be removed?
For example:
Should:
```
If [
 Seq [
  If [ 0 0 0 ]
  If [ 0 0 0 ]
 ]
 Assign : x [ 10 ]
 Assign : x [ 11 ]
]
```
be optimised to
`Assign : x [ 10 ]`

**Comment by m8pple** [comment]
I'm only intending for you to catch the case where it is a constant directly, so
wasn't specifically intending for the further (correct) optimisations.

As far as I know, my test cases can only be optimised for the specific change
that I am expecting.
