### ISSUE TITLE
Is the maximum register/label length 16 characters?

### ISSUE THREAD

**Issue by ThunderMikey** [LangProc/langproc-2017-lab#49]
In the `vm.cpp`, we have, for example,  `sscanf(line.c_str(), "beq %16s %16s %16s", arg1, arg2, arg3)`, which means the VM can only take the first 16 characters of the input register/label name. 

But this limitation is not written in the codegen specification. I found this problem when I was using label names like, `this_is_a_label1234`. After I ran the test-bench, exception was given in the `compiled.stderr.txt` as following:
 `Exception: jump(this_is_a_label1) : No such label.`

P.S. This makes me wonder if our VM truly has an infinite register file.

**Comment by ThunderMikey** [comment]
#47 Ah, I found the answer here.

**Comment by m8pple** [comment]
> P.S. This makes me wonder if our VM truly has an infinite register file.

Yes, you're right - I hadn't even thought of that.

I'll leave the spec alone to avoid confusing people, but I should probably update either
the VM parser or the spec if I run it again.
