### ISSUE TITLE
Error in ref files for hard test of lab 1

### ISSUE THREAD

**Issue by ps-george** [LangProc/langproc-2017-lab#52]
This is sed's output for test 5 of part b:
![image](https://cloud.githubusercontent.com/assets/17267419/23371701/e2735a04-fd10-11e6-86cd-d32e57ec4f7e.png)

The ref has this:
```
ds f 
as d sds a aas d 
````
To emulate sed, should be as above:
```
fds
as d sds a adas
````

**Comment by divyanshmanocha** [comment]
The log seems to say everyone (that I know of) failed this test.

**Comment by m8pple** [comment]
Well, some people (not many) passed this component of the test.
Maybe they would like to comment?

Just in case you're wondering, I do look at all the individual outputs for the hard
tests, so if I see lots of people failing a particular test, I will have investigated and:
1 - decided that it is correct
2 - decided there is enough context for people to work out why it was failing

Not that I claim to be perfect or have perfect systems, so feel free to question
odd results that may have snuck through, but in this instance I'm very much
aware of it as a common failure.

**Comment by ps-george** [comment]
Put the wrong argument when I was testing sed, closing issue.

**Comment by ps-george** [comment]
I thought the error came from reading in the input line by line, because running the individual lines through sed give the output I posted above. But having changed that, the regex_replace with format_sed flag still has a different output to sed.

Why is this? According to the C++ reference , it should `Use the same rules as the sed utility in POSIX to replace matches.`

**Comment by m8pple** [comment]
Nobody who got this test-case correct is biting, so I'll highlight this from the spec:

> Your program should have the same behaviour as the script regex_substitute_ref.sh,
> which you can use for testing. If you look inside the script, you can see it simply invokes sed.

I'll also highlight this, which is the set of options that can be passed to `std::regex::regex`:

http://en.cppreference.com/w/cpp/regex/syntax_option_type

(There is deliberately only one test-case that hits this behaviour).
