### ISSUE TITLE
Minor issue in 1-regexes/ (Examples section)

### ISSUE THREAD

**Issue by wmvndrscht** [LangProc/langproc-2017-lab#53]
In langproc-2017-lab/1-regexes/

In the Examples section
Should output be [abc] 1, instead of [abs] 1

<img width="199" alt="screen shot 2018-01-15 at 21 12 31" src="https://user-images.githubusercontent.com/22416707/34962218-b76f6398-fa3a-11e7-9819-134537a19b61.png">

**Comment by m8pple** [comment]
Thanks - I must have fat-fingered when typing it in. Should have just copied and pasted.
