### ISSUE TITLE
Examples given the input 

### ISSUE THREAD

**Issue by MK2020** [LangProc/langproc-2017-lab#7]
For the input a a a aa -67 -80...

The output you suggested is -6875 " x" 1 "a" 2...

I was wondering why the output of "a" is not 3?

Thanks

**Comment by m8pple** [comment]
> I was wondering why the output of "a" is not 3?

1 - Because I can't count. When I wrote the original spec (before writing the
      reference), I got it wrong. It was then fixed after the spec.
2 - It looks like I introduced a regression going from my reference to the public version
     where I unfixed the fix. Similar to the problems with the reference inputs in other issues.

Thanks for spotting that - I'll update it.
