### ISSUE TITLE
Vagrant file

### ISSUE THREAD

**Issue by alaksana96** [LangProc/langproc-2017-lab#8]
In the Vagrant file, on line 46:

`sudo apt-get -y g++-mips-linux-gnu gdb-multiarch`

When typing it manually on Ubuntu 16.04, we get the error

> E: Command line option 'y' [from -y] is not understood in combination with the other options.

Is it  not meant to be:

`sudo apt-get -y install g++-mips-linux-gnu gdb-multiarch`

**Comment by m8pple** [comment]
Yes, you're right, thanks.

The MIPS stuff is related to the coursework+final lab, so I think everything
I auto-tested with lab didn't rely on the mips stuff. My tests-of-tests
just boot up the VM and try running the test, so I hadn't noticed
the provisioning error.
